### ISSUE TITLE
Cython to_bin() decode error

### ISSUE THREAD

**Issue by pachoo** [libimobiledevice/libplist#109]
When using the cython bindings there are decoding issues with `to_bin` since it tries to decode the binary data into utf-8.

Example:
```
>>> import plist
>>> d = plist.Dict()
>>> d.to_bin()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "plist.pyx", line 112, in plist.Node.to_bin
  File "plist.pyx", line 119, in plist.Node.to_bin
  File "plist.pyx", line 7, in plist._from_string_and_size
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 8: ordinal not in range(128)
```

instead, `Node.to_bin()` should just be returning a byte string

**Comment by nikias** [comment]
Fixed with commit 9c8d7a6c44b0eb22ac77ca6ca5c7c29edd5f685e.
