### ISSUE TITLE
AddressSanitizer: heap-buffer-overflow /home/fuzzer/Fuzzers/libplist/src/bplist.c:586:20 in parse_bin_node

### ISSUE THREAD

**Issue by revskills** [libimobiledevice/libplist#91]
```sh
==19199==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x60e000000847 at pc 0x7fccbc236ccb bp 0x7fffb7380790 sp 0x7fffb7380788
READ of size 8 at 0x60e000000847 thread T0
    #0 0x7fccbc236cca in parse_bin_node /home/fuzzer/Fuzzers/libplist/src/bplist.c:586:20
    #1 0x7fccbc22f571 in parse_bin_node_at_index /home/fuzzer/Fuzzers/libplist/src/bplist.c:680:13
    #2 0x7fccbc23fdf7 in parse_dict_node /home/fuzzer/Fuzzers/libplist/src/bplist.c:411:23
    #3 0x7fccbc239bbc in parse_bin_node /home/fuzzer/Fuzzers/libplist/src/bplist.c:638:16
    #4 0x7fccbc22f571 in parse_bin_node_at_index /home/fuzzer/Fuzzers/libplist/src/bplist.c:680:13
    #5 0x7fccbc22de58 in plist_from_bin /home/fuzzer/Fuzzers/libplist/src/bplist.c:747:14
    #6 0x508155 in main (/opt/libplist_asan/bin/plistutil+0x508155)
    #7 0x7fccbb31b3f0 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x203f0)
    #8 0x419949 in _start (/opt/libplist_asan/bin/plistutil+0x419949)

Address 0x60e000000847 is a wild pointer.
SUMMARY: AddressSanitizer: heap-buffer-overflow /home/fuzzer/Fuzzers/libplist/src/bplist.c:586:20 in parse_bin_node
Shadow bytes around the buggy address:
  0x0c1c7fff80b0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c1c7fff80c0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c1c7fff80d0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c1c7fff80e0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c1c7fff80f0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
=>0x0c1c7fff8100: fa fa fa fa fa fa fa fa[fa]fa fa fa fa fa fa fa
  0x0c1c7fff8110: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c1c7fff8120: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c1c7fff8130: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c1c7fff8140: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c1c7fff8150: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==19199==ABORTING

```

Repro file base64 encoded (Apple binary property list):
```sh
YnBsaXN0MDDSAQIDcF8bc1RhBBBva2VuU3RvcmFnZUtleV8QGWxhenlJbmlUdG1pZVNlY3NTdG9y
ZWRLZXlPEhRreot+omBHr4KlSQHO3MuqWUJURyVA9RgAAAAAAAgNIj5VAAAAAP//////////////
//////////////////8AAAEBAAAAAAAAAAUAAAAAAAAAAAAAAAAAAABe
```
Jfyi a fast and simple fuzzer to catch this issue and others:

```c++
#include "plist/plist.h"
#include <stdio.h>

extern "C" int LLVMFuzzerTestOneInput(const char* data, size_t size) {
        plist_t root_node = NULL;
	plist_from_bin(data, size, &root_node);
	plist_free(root_node);

    return 0;
}
```

**Comment by nikias** [comment]
Thanks! Hehe, I am about to submit a pull request with exactly that code for google's oss fuzz ;)

**Comment by nikias** [comment]
Fixed.
