### ISSUE TITLE
 AddressSanitizer: WRITE of size 4 bplist.c:648:41

### ISSUE THREAD

**Issue by revskills** [libimobiledevice/libplist#92]
```sh
=================================================================
==13546==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x602000000014 at pc 0x7f417b4d71a1 bp 0x7fff4000f750 sp 0x7fff4000f748
WRITE of size 4 at 0x602000000014 thread T0
    #0 0x7f417b4d71a0 in parse_bin_node_at_index /home/fuzzer/Fuzzers/libplist/src/bplist.c:648:41
    #1 0x7f417b4e26bf in parse_array_node /home/fuzzer/Fuzzers/libplist/src/bplist.c:478:23
    #2 0x7f417b4dee99 in parse_bin_node /home/fuzzer/Fuzzers/libplist/src/bplist.c:610:16
    #3 0x7f417b4d7571 in parse_bin_node_at_index /home/fuzzer/Fuzzers/libplist/src/bplist.c:661:13
    #4 0x7f417b4d5e58 in plist_from_bin /home/fuzzer/Fuzzers/libplist/src/bplist.c:728:14
    #5 0x508155 in main (/opt/libplist_asan/bin/plistutil+0x508155)
    #6 0x7f417a5c33f0 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x203f0)
    #7 0x419949 in _start (/opt/libplist_asan/bin/plistutil+0x419949)

0x602000000014 is located 0 bytes to the right of 4-byte region [0x602000000010,0x602000000014)
allocated by thread T0 here:
    #0 0x4cec08 in __interceptor_malloc /home/fuzzer/dev/llvm/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:64
    #1 0x7f417b4d5d79 in plist_from_bin /home/fuzzer/Fuzzers/libplist/src/bplist.c:723:38
    #2 0x508155 in main (/opt/libplist_asan/bin/plistutil+0x508155)
    #3 0x7f417a5c33f0 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x203f0)

SUMMARY: AddressSanitizer: heap-buffer-overflow /home/fuzzer/Fuzzers/libplist/src/bplist.c:648:41 in parse_bin_node_at_index
Shadow bytes around the buggy address:
  0x0c047fff7fb0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c047fff7fc0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c047fff7fd0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c047fff7fe0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c047fff7ff0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x0c047fff8000: fa fa[04]fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fff8010: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fff8020: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fff8030: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fff8040: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fff8050: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==13546==ABORTING

```

Repro file:
```sh
YnBsaXN0MDAAAAAAAAAAAIAAAP////////////////////////8AABAAAAAAAAAAAAAAAP//////
//////////////////////8LKQAAAAAAAP//////AAAA//////////////////8AAAAAAAAAAAAA
AAAAAP////////////8KyykAAAAAAAAAAAAAAAAAACcAAAD///////////////////8A/////wAA
AAAAAAAAAP///////////////////////////////////////////////////////////wEA////
//8AAAD//wAAAAAAAAAA//////////////8AAIEAAAAAAAAAAAAAAP//////////////////////
//////8LKQAAAAAAAP//////AAAA////////////////////////AAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAP//////////////KP8AAAAC/wAAAAAAAAABAAAAAAAAAAAAAAAAAAAA/w==
```
Just catch this the fuzzer after your last commit

**Comment by nikias** [comment]
And fixed. See commit message for details.
